import Head from 'next/head'
import HomePage from '../../components/HomePage/HomePage'
import Header from '../../components/Header/Header'
import { ThemeContext } from '../../context/ThemeContext'
import React, {useContext} from 'react'
import styles from './index.module.css'




export default function Home() {
  const theme = useContext(ThemeContext);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head >
      <main  className={`${styles.main} ${theme?.theme==='dark'? styles.darkMode: ''} `}>
        <Header />
        <HomePage />
             
      </main>
    </>
  )
}
